project:
  type: website
  output-dir: docs

website:
  title: "Karol Orozco"
  
  navbar:
    pinned: true
    background: "#092c3b"
    logo: "images/logo.png"
    align: center
    title: false
    color: "white"
    collapse-below: lg
    
    left:
      - href: index.qmd
        text: About
      - text: DataViz
        href: Resources.qmd
      - text: Models
        href: Projects.qmd


  page-footer: 
    background: light
    left: 
      - "Copyright 2023, Karol Orozco"
      
    right: 
      - icon: github
        href: https://github.com/karolo89
      - icon: linkedin
        href: https://www.linkedin.com/in/karolorozcoe/
      - icon: envelope
        href: mailto:karol.marianoe@gmail.com

  reader-mode: true

format:
  html:
    theme: 
       - html/mystyles.scss
    toc: true
    code-copy: true
    code-fold: true
    code-summary: "Show the code"
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
    mainfont: "Atkinson Hyperlegible"
    include-in-header: "style/fontawesome.html"

freeze: auto

editor: visual

