project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Karol Orozco
      - text: Models
        href: Projects.qmd
      - text: Visualizations
        href: Resources.qmd

  page-footer: 
    background: light
    left: 
      - "Copyright 2023, Karol Orozco"
    right: 
      - icon: github
        href: https://github.com/karolo89
      - icon: linkedin
        href: https://www.linkedin.com/in/karolorozcoe/
      - icon: envelope
        href: mailto:karol.marianoe@gmail.com

  reader-mode: true

format:
  html:
    theme: 
      light: yeti
      dark: slate
    css: styles.css
    page-layout: full
    mainfont: Nunito
    toc: true
    code-fold: true
    code-summary: "Show the code"

editor: visual

