project:
  type: website
  output-dir: docs

website:
  title: "Karol Orozco"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Blog
        href: blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

