project:
  type: website
  output-dir: docs

website:
  title: "Karol Orozco"
  image: "back.png"
  open-graph: true
  
  navbar:
    background: "#092c3b"
    align: center
    title: false
    color: "white"
    collapse-below: lg
    
    right:
      - text: Portfolio
        href: portfolio.qmd
      - text: Resume
        href: CV.qmd
      - href: index.qmd
        text: About Me
      - icon: linkedin
        href: https://www.linkedin.com/in/karolorozcoe/
      - icon: github
        href: https://github.com/karolo89
      - icon: envelope
        href: mailto:karol.marianoe@gmail.com


  page-footer: 
    background: light
    left: 
      - "Blog made with Quarto, Copyright 2023, Karol Orozco"
      

format:
  html:
    theme: 
      light: yeti
      dark: darkly
    css: styles.css
    mainfont: "Futura"
    fontsize: 1.5em
    linestretch: 2
    monofont: "Monaco"
    code-copy: true
    code-fold: true
    code-summary: "Show the code"
    
    
    


freeze: auto

editor: visual

