project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: About
      - text: Blog
        href: blog.qmd
      - text: Projects
        href: Projects.qmd
      - text: Resources
        href: Resources.qmd
  page-footer: 
    background: light
    left: 
      - "Copyright 2023, Karol Orozco"
    right: 
      - icon: github
        href: https://github.com/karolo89
      - icon: linkedin
        href: https://www.linkedin.com/in/karolorozcoe/
  reader-mode: true

format:
  html:
    page-layout: full
    theme: cosmo
    css: styles.css
    mainfont: Nunito
    toc: true

editor: visual

