---
title: "Tables"
author: "Karol Orozco"
date: today
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)

library(tidyverse)
library(dplyr)
library(palmerpenguins)


# prep data
penguins <- penguins %>%
  drop_na()


table_count <- penguins%>%
  group_by(species, sex)%>%
  summarize(count= n())%>%
  select(species, sex, count)

df <- penguins%>%
  group_by(species, sex) %>% 
  summarize(across(where(is.numeric), mean, na.rm = TRUE))%>% 
  dplyr::mutate_if(is.numeric, round, 2)


table <- dplyr::left_join(df, table_count, by= c("species", "sex"))

table<- table%>%
  select("species", "sex", "count", "bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g")%>%
  rename(Culmen_Length = bill_length_mm , 
         Culmen_Depth = bill_depth_mm,  
         Flipper_Length= flipper_length_mm, 
         Body_Mass= body_mass_g,
         Count = count,
         Sex= sex,
         Penguin= species)
```

## Riding Tables with DT

```{r}
library(DT)

datatable(table,

extensions = c('Select', 'Buttons'), options = list(
    select = list(style = 'os', items = 'row'),
    dom = 'Blfrtip',
    rowId = 0,
    buttons = c('selectAll', 'selectNone', 'selectRows', 'selectColumns', 'selectCells')
  ),
  selection = 'none',
    
          caption = htmltools::tags$caption(
    style = 'caption-side: bottom; text-align: center;',
    'Table 1: ', htmltools::em('Data were collected and made available by Dr. Kristen Gorman and the Palmer Station, Antarctica LTER, a member of the Long Term Ecological Research Network.')
  ))

```

## Riding Tables with gt & gtExtra




```{r}

library(gt)
library(gtExtras)

table%>%
  gt()%>%
  
  tab_header(
    title = "Penguins are fun to summarize!",
  # Use markdown syntax with md()
    subtitle = md("The palmerpenguins: Palmer Archipelago (Antarctica) penguin data"))%>%
  
  gtExtras::gt_theme_nytimes()%>%
  
  tab_options(data_row.padding = px(9))%>%
  
  # Merge columns
  gtExtras::gt_merge_stack(col1 = Penguin, col2 = Sex)
```


## Reference

Horst AM, Hill AP, Gorman KB (2020). palmerpenguins: Palmer
Archipelago (Antarctica) penguin data. R package version 0.1.0.
https://allisonhorst.github.io/palmerpenguins/. doi:
10.5281/zenodo.3960218.


`

